import { UserRole } from '../enums/roles.enum';
import { Permission } from '../enums/permissions.enum';

const ALL_PERMISSIONS = Object.values(Permission);

const MANAGER_PERMISSIONS = [
  Permission.DASHBOARD_VIEW,
  Permission.USERS_VIEW,
  Permission.LBC_VIEW,
  Permission.LBC_EDIT,
  Permission.AGENTS_VIEW,
  Permission.AGENTS_EDIT,
  Permission.AGENTS_TRANSFER,
  Permission.FARMERS_VIEW,
  Permission.FARMERS_APPROVE,
  Permission.FARMERS_EDIT,
  Permission.FARMS_VIEW,
  Permission.FARMS_EDIT,
  Permission.PRODUCE_VIEW,
  Permission.PRODUCE_MANAGE,
  Permission.PRODUCE_APPROVE,
  Permission.WAREHOUSES_VIEW,
  Permission.LOGISTICS_VIEW,
  Permission.LOGISTICS_MANAGE,
  Permission.TRACKING_VIEW,
  Permission.TRACKING_REALTIME,
  Permission.PAYMENTS_VIEW,
  Permission.PAYMENTS_APPROVE,
  Permission.REPORTS_VIEW,
  Permission.REPORTS_EXPORT,
  Permission.ANALYTICS_VIEW,
  Permission.NOTIFICATIONS_VIEW,
  Permission.AUDIT_VIEW,
  Permission.SETTINGS_VIEW,
  Permission.CUSTOMERS_VIEW,
  Permission.CUSTOMERS_CREATE,
  Permission.CUSTOMERS_EDIT,
  Permission.CUSTOMERS_VERIFY,
  Permission.CUSTOMERS_ORDERS,
  Permission.CUSTOMERS_WALLET,
  Permission.CUSTOMERS_NOTIFICATIONS,
  Permission.CUSTOMERS_ANALYTICS,
  Permission.CUSTOMERS_REPORTS,
];

export const ROLE_PERMISSIONS: Record<UserRole, Permission[]> = {
  [UserRole.SUPER_ADMIN]: ALL_PERMISSIONS,

  [UserRole.OPERATIONS_MANAGER]: MANAGER_PERMISSIONS,

  [UserRole.REGIONAL_MANAGER]: [
    Permission.DASHBOARD_VIEW,
    Permission.AGENTS_VIEW,
    Permission.AGENTS_EDIT,
    Permission.AGENTS_TRACK,
    Permission.FARMERS_VIEW,
    Permission.FARMERS_APPROVE,
    Permission.FARMS_VIEW,
    Permission.PRODUCE_VIEW,
    Permission.PRODUCE_MANAGE,
    Permission.LOGISTICS_VIEW,
    Permission.TRACKING_VIEW,
    Permission.TRACKING_REALTIME,
    Permission.REPORTS_VIEW,
    Permission.ANALYTICS_VIEW,
    Permission.NOTIFICATIONS_VIEW,
    Permission.CUSTOMERS_VIEW,
    Permission.CUSTOMERS_ORDERS,
    Permission.CUSTOMERS_ANALYTICS,
    Permission.CUSTOMERS_REPORTS,
  ],

  [UserRole.LBC_MANAGER]: [
    Permission.DASHBOARD_VIEW,
    Permission.LBC_VIEW,
    Permission.AGENTS_VIEW, 
    Permission.AGENTS_CREATE, 
    Permission.AGENTS_EDIT,
    Permission.FARMERS_VIEW, 
    Permission.FARMERS_CREATE,
    Permission.FARMS_VIEW,
    Permission.PRODUCE_VIEW,
    Permission.TRACKING_VIEW,
    Permission.REPORTS_VIEW,
    Permission.NOTIFICATIONS_VIEW,
  ],

  [UserRole.FINANCE_MANAGER]: [
    Permission.DASHBOARD_VIEW,
    Permission.PAYMENTS_VIEW,
    Permission.PAYMENTS_APPROVE,
    Permission.PAYMENTS_PROCESS,
    Permission.PAYMENTS_REFUND,
    Permission.REPORTS_VIEW,
    Permission.REPORTS_EXPORT,
    Permission.ANALYTICS_VIEW,
    Permission.ANALYTICS_ADVANCED,
    Permission.AUDIT_VIEW,
    Permission.NOTIFICATIONS_VIEW,
    Permission.CUSTOMERS_VIEW,
    Permission.CUSTOMERS_WALLET,
    Permission.CUSTOMERS_ORDERS,
    Permission.CUSTOMERS_ANALYTICS,
    Permission.CUSTOMERS_REPORTS,
  ],

  [UserRole.WAREHOUSE_MANAGER]: [
    Permission.DASHBOARD_VIEW,
    Permission.WAREHOUSES_VIEW, 
    Permission.WAREHOUSES_MANAGE, 
    Permission.WAREHOUSES_INVENTORY,
    Permission.PRODUCE_VIEW, 
    Permission.PRODUCE_APPROVE,
    Permission.LOGISTICS_VIEW,
    Permission.REPORTS_VIEW,
    Permission.NOTIFICATIONS_VIEW,
  ],

  [UserRole.LOGISTICS_MANAGER]: [
    Permission.DASHBOARD_VIEW,
    Permission.LOGISTICS_VIEW, 
    Permission.LOGISTICS_MANAGE, 
    Permission.LOGISTICS_DISPATCH,
    Permission.TRACKING_VIEW, 
    Permission.TRACKING_REALTIME,
    Permission.REPORTS_VIEW,
    Permission.NOTIFICATIONS_VIEW,
  ],

  [UserRole.QA_OFFICER]: [
    Permission.DASHBOARD_VIEW,
    Permission.PRODUCE_VIEW, 
    Permission.PRODUCE_APPROVE,
    Permission.FARMERS_VIEW,
    Permission.FARMS_VIEW,
    Permission.WAREHOUSES_VIEW,
    Permission.REPORTS_VIEW,
    Permission.NOTIFICATIONS_VIEW,
  ],

  [UserRole.CUSTOMER_SUPPORT]: [
    Permission.DASHBOARD_VIEW,
    Permission.FARMERS_VIEW,
    Permission.AGENTS_VIEW,
    Permission.LBC_VIEW,
    Permission.PAYMENTS_VIEW,
    Permission.NOTIFICATIONS_VIEW,
    Permission.NOTIFICATIONS_SEND,
    Permission.REPORTS_VIEW,
    Permission.CUSTOMERS_VIEW,
    Permission.CUSTOMERS_EDIT,
    Permission.CUSTOMERS_ORDERS,
    Permission.CUSTOMERS_WALLET,
    Permission.CUSTOMERS_NOTIFICATIONS,
    Permission.CUSTOMERS_REPORTS,
  ],

  [UserRole.AUDITOR]: [
    Permission.DASHBOARD_VIEW,
    Permission.AUDIT_VIEW,
    Permission.REPORTS_VIEW, 
    Permission.REPORTS_EXPORT,
    Permission.USERS_VIEW,
    Permission.PAYMENTS_VIEW,
    Permission.LBC_VIEW,
  ],

  [UserRole.ANALYST]: [
    Permission.DASHBOARD_VIEW,
    Permission.ANALYTICS_VIEW,
    Permission.REPORTS_VIEW,
    Permission.FARMERS_VIEW,
    Permission.AGENTS_VIEW,
    Permission.LBC_VIEW,
  ],
};
